version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      ci-infrastructure:
        patterns:
          - "actions/checkout"
          - "actions/cache"
      ci-tools:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
    open-pull-requests-limit: 5
